### ISSUE TITLE
Unable To Decode Walmart Issuer Data Due to Non Standard String In Type

### ISSUE THREAD

**Issue by hiteshmehramca** [the-commons-project/vci-directory#151]
We are getting below mention issue in one scenario.

One of the VerifiableCredentialTypes (vc.type) was not an allowed value, type found was: VerifiableCredential. 
The supported types are:
https://smarthealth.cards#covid19,
https://smarthealth.cards#health-card,
https://smarthealth.cards#immunization,
https://smarthealth.cards#laboratory

Decoded Token has a non standard string highlighted below. Going by the specifications (https://spec.smarthealth.cards/vocabulary/) , this is not a valid type, so validation error thrown is correct. And we didn’t see such issue for any other Issuer.

type: [
"VerifiableCredential",
"https://smarthealth.cards#health-card",
"https://smarthealth.cards#immunization",
"https://smarthealth.cards#covid19"
]

As we are getting not standard string in type we are not able to decode from the Walmart issuer.

**Comment by jdkizer9** [comment]
Hi @hiteshmehramca, depending on your application, it _may_ make sense for you to simply ignore any `type` values that that you are not specifically looking for. A [PR](https://github.com/the-commons-project/vci-directory/issues/151) for similar guidance has been added to the SMART Health Card specs.
