### ISSUE TITLE
Health Cards from MyIR aren't passing validation

### ISSUE THREAD

**Issue by jmandel** [the-commons-project/vci-directory#179]
Tracking issue -- can resolve when tests at https://github.com/smart-on-fhir/health-cards-dev-tools are passing

**Comment by jmandel** [comment]
This issue was scoped on technical validity of the SMART Health Cards -- a prerequisite for membership in the VCI Directory that is now satisfied.

> Presumably one form per issuer that MyIR is representing will need to be submitted.

VCI is working with the MyIR team on this.

**Comment by acohe** [comment]
Hi, I think we need to reopen this issue because the MyIR QR codes are still not verifying on SMART systems. Do we have a timeline for resolving this?

**Comment by acohe** [comment]
@laurencebgood @jmandel @modest 
Please see attached image. The QR code scans and is parsed to show the correct person with the correct vaccines…however it says “Partially Verified” which means that the QR code will not allow that person to travel. 
![Uploading 5E42AE3B-C0E9-44F4-9FD8-7B38121DFAE1.jpeg…]()

**Comment by acohe** [comment]
@laurencebgood @jmandel @modest 
Please see attached image. The QR code scans and is parsed to show the correct person with the correct vaccines…however it says “Partially Verified” which means that the QR code will not allow that person to travel. 
![Uploading 5E42AE3B-C0E9-44F4-9FD8-7B38121DFAE1.jpeg…]()

**Comment by acohe** [comment]
@laurencebgood How can we accelerate this timeline? This is an issue impacting tens of thousands of people who can’t travel or see their families without this. But I don’t get a sense that anyone feels any urgency…

How can we get Common Trust Verifier (CTV) to recognize MyIR (and the Canadian APIs)? Who at CTV is in charge of that?  

Who is in charge of getting the VCI directory integrated with the verification process? How do we get them more involved in this process?
