### ISSUE TITLE
University of Michigan Health-West keyset fetch failing with 404

### ISSUE THREAD

**Issue by jdkizer9** [the-commons-project/vci-directory#267]
@BenjaminatEpic can you look into this? https://github.com/the-commons-project/vci-directory/runs/4069956794?check_suite_focus=true

Thanks!

**Comment by BenjaminatEpic** [comment]
Thanks for letting us know! I'll post an update here when the issue is resolved.

**Comment by BenjaminatEpic** [comment]
@jdkizer9 This should be resolved now.

**Comment by jdkizer9** [comment]
Thanks @BenjaminatEpic
