### ISSUE TITLE
Why are some major provider not included in vci-issuers.json? 

### ISSUE THREAD

**Issue by MA1GitHub** [the-commons-project/vci-directory#273]
Some major providers like Walmart and CVS are not included in vci-issuers.json. Does this file include all official providers in the US?

**Comment by laurencebgood** [comment]
What's an "official provider"? I don't think there even is such a thing. Generally, if an issuer isn't listed in the VCI directory, it means they haven't submitted a request to be listed (or did so without agreeing to the terms that must be agreed to as a condition of being listed). See #30 for general discussion of this topic.

**Comment by MA1GitHub** [comment]
> What's an "official provider"? I don't think there even is such a thing. Generally, if an issuer isn't listed in the VCI directory, it means they haven't submitted a request to be listed (or did so without agreeing to the terms that must be agreed to as a condition of being listed). See #30 for general discussion of this topic.

Official provider means a provider or an organization that is approved by the government (not a fake one).

**Comment by laurencebgood** [comment]
> > What's an "official provider"? I don't think there even is such a thing. Generally, if an issuer isn't listed in the VCI directory, it means they haven't submitted a request to be listed (or did so without agreeing to the terms that must be agreed to as a condition of being listed). See #30 for general discussion of this topic.
> 
> Official provider means a provider that is approved by the government (not a fake one).

You mean like, for example, licensed as a pharmacy, hospital, or healthcare provider? I don't think there's any government approval specific to covid vaccination credentials.

**Comment by MA1GitHub** [comment]
> > > What's an "official provider"? I don't think there even is such a thing. Generally, if an issuer isn't listed in the VCI directory, it means they haven't submitted a request to be listed (or did so without agreeing to the terms that must be agreed to as a condition of being listed). See #30 for general discussion of this topic.
> > 
> > 
> > Official provider means a provider that is approved by the government (not a fake one).
> 
> You mean like, for example, licensed as a pharmacy, hospital, or healthcare provider? I don't think there's any government approval specific to covid vaccination credentials.

That's exactly what I meant. 
So, if an organization  submitted a request to be included in the VCI directory, are there any kind of verification  done on this organization before it gets added to the directory?

**Comment by p9g** [comment]
See https://github.com/the-commons-project/vci-directory/pull/249
