### ISSUE TITLE
New `iss` for UNC Health?

### ISSUE THREAD

**Issue by jdkizer9** [the-commons-project/vci-directory#293]
Hi @BenjaminatEpic,

We've gotten some reports of some SHCs issued from UNC Health that are not being recognized by the SMART Health Card Verifier. It looks like they are being issued with a different `iss` value (see attached screenshot) than what is provided here in the directory. Do you know what might be going on?

Thanks!

![IMG_1204](https://user-images.githubusercontent.com/6721921/140658337-df9666db-3bfb-401e-97d5-8c9db1790d76.jpg)

**Comment by BenjaminatEpic** [comment]
@jdkizer9 On it! We're following up with UNC and determining if they need to add this as a CanonicalIss

**Comment by jdkizer9** [comment]
Thanks @BenjaminatEpic, fixed per #298
