### ISSUE TITLE
`https://emrrp.ucdmc.ucdavis.edu/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC` failing due to 404 status

### ISSUE THREAD

**Issue by jdkizer9** [the-commons-project/vci-directory#299]
@BenjaminatEpic can you look into this?

Also, I'm having @edwardjcruz help with merging some of the new issuers in. The checks that we currently have in place prevent merging of pull requests unless all issuers are passing validation. My concern is that as the list grows, the amount of time that one or more existing issuers is down will also grow. Any thoughts on how we can address this?

cc: @isaacvetter

**Comment by BenjaminatEpic** [comment]
@jdkizer9 Just got word that this was back up. I noticed this when I made the first PRs for today and they got to work on it and just fixed it.

**Comment by isaacvetter** [comment]
related to #318
