### ISSUE TITLE
VCI directory missing issuers allowed by Commons project verifier android app

### ISSUE THREAD

**Issue by laurencebgood** [the-commons-project/vci-directory#30]
Apologies if this is the wrong place to ask this, but I haven't found anywhere that seems better. The Commons Project has released a verifier app, the android version is at https://play.google.com/store/apps/details?id=com.thecommonsproject.smarthealthcardverifier 

I have been wondering what the relationship between the VCI directory and the app is, because I note the app verifies Walmart-issued SHCs successfully, but Walmart is not currently in this directory. I tried to find the source for the app to answer this myself, but it doesn't seem to be published anywhere.

I ask because I am interested in easier verification methods for small businesses, but doing so usefully will require a good directory of trusted SHC issuers, and I think that's the intention of this directory, but then the Commons Project seems to be using a separate directory for its own app, and this is very confusing.

Thanks in advance for any guidance or information you can provide,
Laurence

**Comment by Anvay** [comment]
+1. Would like to know how small scale health providers join the Common Trust Network. We plan on issuing shc and would not be ideal for getting partial verification.

Thanks
A

**Comment by jpp9** [comment]
thank you both for these comments- i hear you on the confusion. issuers request to be added to the VCI Directory by completing an attestation form and meeting the criteria described in the readme and agreement docs in the repo. the criteria don't account for the longer tail of issuers, but we hope represent a good starting point as we figure out what this directory should be and how it will be used. we do encourage everyone who fits to join, but haven't gotten 100% buy in (yet).

the SMART Health Card Verifier app does rely on the CommonTrust Network, which is based on the VCI Directory, but also proactively includes some legitimate orgs issuing proper SMART Health Cards who haven't yet joined VCI Directory for whatever reason. if you're issuing SMART Health Cards and want to be included in CommonTrust Network, you can provide info here: https://www.commontrustnetwork.org/join.

thanks!

**Comment by laurencebgood** [comment]
@jpp9 thanks for the explanation. If one is interested in being able to use the list the CommonTrust network is using to do verifications, are verifiers able to join? I see it seems targeted towards organizations, but I'm not sure if an open source project qualifies

**Comment by laurencebgood** [comment]
I notice that Walmart is now listed as a member of VCI per https://vci.org/about yet still is not listed in this directory.

Meanwhile, British Columbia provincial SHCs are being accepted by the common trust verifier but aren't even listed at https://www.commontrustnetwork.org/verifier-list

Meanwhile, tweets from the Commons project frequently refer to the VCI as the basis for trusting issuers. Eg https://twitter.com/commons_prjct/status/1440699255820226574?s=19  So this situation just gets more and more confusing. It's not clear if anyone is actually using the directory here, and it's not obvious to most what the difference is between this directory, the list for common trust, and the (secret?) list of acceptable issuer kids actually being used by the common trust verifier app. Clarity on this would be a big improvement as more issuers, both private and government, spin up.

I'm passionate enough about this that I'm interested in helping, but it's hard to understand if there's an opportunity for that in the organizational structure that exists.

**Comment by awensaunders** [comment]
> Meanwhile, British Columbia provincial SHCs are being accepted by the common trust verifier but aren't even listed at https://www.commontrustnetwork.org/verifier-list

They're now on that list, but they aren't in the vci-issuers.json. Is commontrust listing them without them having done their paperwork, or have they just not made it into the .json file yet for some reason?

**Comment by laurencebgood** [comment]
@bradhead this GitHub repo isn't listing BC, so I believe you are going to need to take that up with the people who make the verifier app in question. I haven't seen anything publicly stated about BC's position on this, though.

That said, are you affiliated with the BC government in some way? Because the BC verifier app does not accept out of province vaccination SHCs, and that sure was a fun experience for me. Mostly places would briefly get frustrated and then check it manually. One place said they were doing me a favor by letting me dine and that I would need a BC issued SHC next time. Hopefully someone corrected them before they started refusing vaccinated patrons from out of the province. I suspect a motivation for verifiers to use another app, such as the one you are complaining about, will be to validate SHCs from outside the province, so if you are from the BC government, perhaps you could escalate getting the BC verifier app to accept cards from other provinces, American states, and other issuers down the line? Otherwise, there's an incentive for verifiers to not use the official app.

**Comment by laurencebgood** [comment]
@jpp9 thanks for the thoughtful response. I understand how in general that decision by Common Trust makes sense. The normalization you describe will be a big positive, and I'm glad to hear it will be happening. It resolves the core of what I opened this issue for in the first place.

A couple of points this all raises, though:

1) the CommonTrust network has also included Walmart in their app for quite a while. I don't know if that's the only non-governmental addition they have made, but it's a pretty big one. I'm not necessarily saying this is a problem, but it does suggest that it would be preferable for Common Trust to be more explicit about their criteria for proactive inclusion, so verifiers can make informed choices. VCI has a very explicit inclusion criteria explained right here in this repo, so if that's going to remain the same, normalization between VCI and CommonTrust network will fully resolve this. (It's a bit odd that Walmart has been issuing SHCs for so long but still isn't present here in the VCI directory-will they be getting removed from the CommonTrust network if they don't want to agree to the VCI terms when normalization happens?). 

2) Normalization would address @bradhead's concern if the VCI inclusion policy isn't changing thus causing the CommonTrust network's list to follow the same inclusion policy, which among other things requires an explicit opt-in, and so would result in BC's removal from CommonTrust network's list. Or is the policy going to change in some way, such as including obviously reasonable issuers like governments, and if so will it permit opt out? Is there a plan yet? (I have my own opinions on opt in, opt out, etc but that's a conversation better to have separately from this issue, maybe a conversation instead of an issue, if someone even wants to hear them)

3) the government of Singapore is going to start allowing the use of SHCs to prove vaccination status for their "vaccinated travel lane" program in less than 4 days. For the moment, they are allowing issuers from both VCI and CommonTrust https://safetravel.ica.gov.sg/vtl/faq#Q7 but it's not clear how they are going to check that in practice. Do they have access to CommonTrust's issuers list? Do they know that there may be VCI-listed issuers who aren't included in CommonTrust's verifier app? Not really clear. But does kind of put a finer point on it. When the lists are normalized, this concern goes away, but I wanted to call this out because it's the first time I've seen a government specify issuer lists for SHCs, and I am guessing this will become more common. (Also, @bradhead, if BC is delisted from all these verification lists, that would either require getting the gov of Singapore to specifically allow BC SHCs anyway, or it would exclude those vaccinated in BC from Singapore's VTL program)


As for what @modest is talking about, what's surprising to me is that vaccinecheck.me is selling cards it is issuing using the issuer it created for a county. @modest, did you pay for their service in order to get a sample? I am curious because their website suggests their verification process is fairly thorough, but I have no idea whether or not it actually is. (Whether or not purchased SHCs should be included in VCI, I don't know, if some entities are intentionally making it hard for people to get verifiable vaccine credentials, and they are doing significant work in order to verify the genuineness of a purchaser's vaccination despite this, then maybe that's okay-I have opinions on this, too, but again if someone wants to hear them, this issue isn't the place, and a conversation would probably be better than another issue)

As a practical matter, @jpp9, should the VCI agreement be amended to require providers that work on behalf of multiple "notional" issuers be required to use a separate iss URL for each one? The agreement incorporates documentation and best practices that kind of implies it, but isn't explicit about it. Both Cerner and epic have been doing exactly this. Interestingly, vaccinecheck is doing this as well-they issue for several Maryland counties, and use a different iss URL for each one. Given that, I'm surprised they are selling individuals an SHC that uses the same iss as they created for Wicomico county. Perhaps this is merely an oversight on their part? I'm hoping so.

(wow that's a lot of text, oof, sorry, thanks for reading it all!)

**Comment by Manouchehri** [comment]
@modest Thanks for doing all the initial research. Have you done any further reverse engineering of the closed source app? Would be interesting to know the findings. =)
