### ISSUE TITLE
Pull Request directory checks are inconsistent, and test beyond the endpoint submission

### ISSUE THREAD

**Issue by BenjaminatEpic** [the-commons-project/vci-directory#318]
Could we localize the checks to the added endpoints to allow the PRs to pass when the errors are unrelated to the endpoint modified, or potentially recheck failures with a small grace period? The end effect currently is that some errors are issued, which by the time they are examined, are no longer apparent errors. 

Example: UPMC's endpoint threw an error in the "add County of Santa Clara Health System" PR, but when examined showed no signs of an error. The "add Dartmouth-Hitchcock Health" endpoint, which was added very shortly after passed with no endpoints.

**Comment by jdkizer9** [comment]
@BenjaminatEpic I spent a bit of time trying to figure out how to do this, but I didn't come up with much. My thought was that we might be able to diff between the PR branch and the main branch, and then just check the diffs. However, I wasn't able to figure out a way to do so. Happy to accept a PR if you can figure it out!

**Comment by BenjaminatEpic** [comment]
I experienced the inconsistency issue a second ago and checked the endpoint - the HTML error given in the checks matches a browser recording a 403 error for the favicon. Is this something that could possibly be contributing to inconsistent/benign errors?
