### ISSUE TITLE
Some of the URLS for the Issuers are causing issues

### ISSUE THREAD

**Issue by deschandhok24** [the-commons-project/vci-directory#325]
When I make a get request to these urls below they are causing issues:

1. 
**URL:** https://tpc-shield.tpcllp.com/FHIR/api/epic/2021/Security/Open/EcKeys/32001/SHC/.well-known/jwks.json 
**Issue:** Connection reset by peer - SSL_connect. Cant even open this link in a browser.

2.
**URL:** https://www.gov.nl.ca/covid-19/life-during-covid-19/vaccination-record/prod/.well-known/jwks.json
**Issue:**  When I try to parse the body of the response I get an error due to a malformed JSON String -> this is because the response body is not a valid JSON string.

3.
**URL:** https://api.ccf.org/mu/api/epic/2021/Security/Open/EcKeys/32001/SHC/.well-known/jwks.json
**Issue:** I keep getting a Spike arrest violation even though I have looked at it 3-4 times within the last 2 days.

Can someone please help by looking into this further and contacting the issuers themselves to make some changes on their ends.

**Comment by jdkizer9** [comment]
@deschandhok24 I'm not seeing any issues with #2, I get the following output:

```
{
    "keys": [
        {
            "kty": "EC",
            "kid": "UboztS3pE1mr0dnG7Rv24kRNqlYbHrbxd-qBFerpZvI",
            "use": "sig",
            "alg": "ES256",
            "crv": "P-256",
            "x": "mB0PKTVRnr3JCtyucEjCHXkXW3COg5KP0y4gKCNJxWc",
            "y": "PTpxiYECNiuyRwpwqjme8OIFdG7N-HwN2XH02phdZCs",
            "date": 1632779181394
        }
    ]
}
```

@BenjaminatEpic can you look into the other 2 issues?

Thanks!

**Comment by deschandhok24** [comment]
@jdkizer9 thanks for looking into this.


I am using ruby and make a get request via the httpParty library.

For 2)

`
url = 'https://www.gov.nl.ca/covid-19/life-during-covid-19/vaccination-record/prod/.well-known/jwks.json'
res = HTTParty.get(url)
data = JSON.parse(res.body)
`

Error this returns
`JSON::ParserError: 784: unexpected token at '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3c.org/TR/1999/REC-html401-19991224/loose.dtd">`

**Comment by isaacvetter** [comment]
1) I can open this url in a browser ... also appears to be either resolved or at least intermittent.

3) Spike arrests needn't be per requestor. Given that this is a completely unauthenticated endpoint, there isn't really a great way to group requests per client. It seems like a spike arrest should be considered a reasonable, temporary error and the client should retry.
