### ISSUE TITLE
New Brunswick not in directory

### ISSUE THREAD

**Issue by Curtistic** [the-commons-project/vci-directory#334]
The Government of New Brunswick has begun its smart health card program. Could the iss be added to the directory?

"iss": "https://www.gnb.ca/smarthealth",
      "name": "Government of New Brunswick"

**Comment by laurencebgood** [comment]
added by @edwardjcruz earlier today in #387

**Comment by spncrd** [comment]
@Curtistic with NB now supported along with all other territories and provinces in Canada, I think we can close this.
