### ISSUE TITLE
Ontario's server blocking other VCI members

### ISSUE THREAD

**Issue by Manouchehri** [the-commons-project/vci-directory#365]
After https://github.com/the-commons-project/vci-directory/pull/358 was merged, I realized that they are blocking the _entire_ Cayman Islands (which is even a CommonTrust member). This is in direct violation of rule 7 in the VCI directory agreement. https://github.com/the-commons-project/vci-directory/blob/main/VCI%20Directory%20Agreement.pdf

@edwardjcruz @spncrd Could you please remove _all_ the country blocks you have on Amazon CloudFront immediately? Both `https://prd.pkey.dhdp.ontariohealth.ca/` and `https://covid19.ontariohealth.ca/` being blocked.

![image](https://user-images.githubusercontent.com/7232674/143145581-6177e314-d5a7-4c3c-9f2e-68485af69da4.png)

```
403 ERROR
The request could not be satisfied.
The Amazon CloudFront distribution is configured to block access from your country. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: ibRurI4C4vMndE9-SGIBXrQ-spVQ34C-HbS-zmFsxb_gk89AXBnEBg==
```

**Comment by laurencebgood** [comment]
While I am supportive of dropping all the country blocks, my read of the agreement (as an unaffiliated observer) is that rule 7 would specifically be about https://prd.pkey.dhdp.ontariohealth.ca/.well-known/jwks.json @Manouchehri would you please confirm whether that is available from eg Cayman Islands?

**Comment by Manouchehri** [comment]
I can confirm 100% that `https://prd.pkey.dhdp.ontariohealth.ca/.well-known/jwks.json` is being blocked from the Cayman Islands. I attempted to connect over ASN36549 (WestTel Ltd.) and ASN30689 (Flow), both are denied access.

![image](https://user-images.githubusercontent.com/7232674/143151101-f5f1a9ee-1e0f-4e50-877b-fad579e950fb.png)

![image](https://user-images.githubusercontent.com/7232674/143151457-01317d95-cda1-48bc-a1cc-8d1bdd282121.png)

**Comment by Manouchehri** [comment]
> While I am supportive of dropping all the country blocks, my read of the agreement (as an unaffiliated observer) is that rule 7 would specifically be about https://prd.pkey.dhdp.ontariohealth.ca/.well-known/jwks.json @Manouchehri would you please confirm whether that is available from eg Cayman Islands?

@laurencebgood It appears that somebody from Ontario Health read your comment and complied.

`https://prd.pkey.dhdp.ontariohealth.ca/.well-known/jwks.json` appears to have been unblocked for Cayman. `https://covid19.ontariohealth.ca/` still seems to be blocked, but I guess it technically isn't breaking the rules for VCI anymore..

**Comment by spncrd** [comment]
@Manouchehri I did share with our MOH IT colleagues and glad to hear at least the key has been unblocked. If there are any more geo-fencing issues, happy to pass them along. There does not seem to be desire, at this time, to remove all geo-fencing and to instead provide targeted lifts.

**Comment by gflood** [comment]
@edwardjcruz @spncrd hi would it be possible to also open this up to Ireland? 

"An exception occurred while attempting to connect to the Smarthealth card issuer at: https://prd.pkey.dhdp.ontariohealth.ca/.well-known/jwks.json.  Exception: 403 Forbidden:...
The Amazon CloudFront distribution is configured to block access from your country."

Many Thanks
