### ISSUE TITLE
Augment directory with metadata

### ISSUE THREAD

**Issue by jmandel** [the-commons-project/vci-directory#52]
Fields that would be helpful to add to the issuer schema:

* `website`: Link to a website for the issuer. Following this link should lead to a web page where individuals can interact with the issuer (e.g., to request help, or learn how to request a copy of their data as a SMART Health Card)
* `securityContact`: E-mail address to contact this issuer to report security issues
* `canonicalIss`: if the issuer has migrated to a new `iss` value, this field conveys the new (canonical) `iss`
* `attestedToVciAgreement`: boolean, or date indicating whether/when the issuer attested to the terms https://github.com/the-commons-project/vci-directory/blob/main/VCI%20Directory%20Agreement.pdf (this paves the way for listing issuers that have not yet attested, if we have other reasons to think they're reliable sources of SMART Health Cards)
* `healthCardTypes`: array of space-separated strings, conveying the sets of types an issuer is allowed to issue. For an issuer that does only COVID-19 immunizations the value would be
  * `["https://smarthealth.cards#health-card https://smarthealth.cards#covid19 https://smarthealth.cards#immunization"]`

**Comment by p9g** [comment]
Just a thought: define a new ".well-known" document that is accessed from the iss.  Now we append "/.well-known/jwks.json" to the iss; how about append "/.well-known/smarthealth.json", and put the info you suggest above in it.

**Comment by jmandel** [comment]
That decentralization would be helpful for managing updates; at the same time, it makes it hard for VCI to add endpoints to the directory when the issuer isn't actively involved (e.g., if the issuer hasn't yet attested and hasn't supplied this metadata in their own .well-known file, we might still want to list them and their data).

(If we can get the data model right, it's always possible to be flexible on who publishes these data -- like, grabbing the data from the issuer's discovery document if available, or layering on data in the VCI directory if not, or if we need to override things. So my preference would be to work through the data model in this issue, and then separately talk through the deployment model, unless you think our design choices on these two would be inter-dependent.)

**Comment by p2-apple** [comment]
Some initial thoughts:

- `website`: would be helpful indeed; we'd need to specify rules on how VCI verifies that the provided website does indeed belong to the issuer
- `securityContact`: Yes! Is an email enough or does it need to also take URLs (like a link to an incident form)?
- `canonicalIss`: 👍🏼
- `attestedToVciAgreement`: could this become tricky? E.g. private issuers are added that have not attested to the agreement and therefore the use of their name/logo isn't covered. Governmental issuers would also receive a `false` here, however the use of their name I believe would still be ok, even if nobody has attested.
- `healthCardTypes`: I like this idea as moving a step towards a trust framework. This will also need a thorough guide on who decides which issuer gets a sign-off on which types based on what facts. Probably a good thread to start within VCI, but I'm assuming this will spawn more trust talk, along the lines of "the State of California endorses issuer X for card types a, b, and c". No doubt important to have this discussion!

**Comment by isaacvetter** [comment]
How about we start with just `website` and `canonicalIss` so that we can get it done quickly? 
* There's already some orgs in the directory with multiple entries; we need `canonicalIss` by like last month. 
* And website seems pretty easy. 

And make both fields optional.

**Comment by jmandel** [comment]
Makes sense to me to pull off these two properties for a quick start. @jdkizer9 would a PR here help? e.g. updating python validation, or adding a JSON Schema defining the relevant properties?

**Comment by jdkizer9** [comment]
Sure, this sounds good to me. What are the requirements for the `website` and `canonicalIss` props? `website` should resolve? `canonicalIss` should be included as another entry in the directory?

**Comment by jmandel** [comment]
Yes

* `website` should resolve (potentially after redirects) to something with a 2xx status
* `canoniaclIss` if present should be an `iss` that appears in the directory

**Comment by isaacvetter** [comment]
and James, if it would be helpful, we've got that one organization with two entries already, who could be a good pilot case for canonicalIss.

**Comment by jdkizer9** [comment]
@isaacvetter sure, that would be great! I'll have a PR up for this tonight, but if you could let me know the entry with the `canonicalIss` value, I'll add it.

**Comment by jdkizer9** [comment]
@jmandel @isaacvetter @p2-apple @p9g I've created #129 to add support for the new metadata fields. Have a look when you have a chance

**Comment by isaacvetter** [comment]
James, I was thinking of UCSD. We've got these two:
```
    {
      "iss": "https://epicproxy.et0502.epichosted.com/EPPARRPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC",
      "name": "UC Health (San Diego / Irvine / Riverside) and Affiliates"
    },
    {
      "iss": "https://epicproxy-pub.et0502.epichosted.com/EPPARRPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC",
      "name": "UC Health (San Diego / Irvine / Riverside) and Affiliates"
    }
```
which should become, I think:
```
    {
      "iss": "https://epicproxy-pub.et0502.epichosted.com/EPPARRPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC",
      "name": "UC Health (San Diego / Irvine / Riverside) and Affiliates",
      "canonical_iss":      "iss": "https://epicproxy.et0502.epichosted.com/EPPARRPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC"
    }
```

`canonical_iss` is the new url, right? Such that over time there may be multiple entries, each which the same canonical_iss ?

**Comment by isaacvetter** [comment]
Except, there's going to be a lag for apps to support this syntax, so maybe the safer approach for now, would be:
```
    {
      "iss": "https://epicproxy.et0502.epichosted.com/EPPARRPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC",
      "name": "UC Health (San Diego / Irvine / Riverside) and Affiliates",
    },
    {
      "iss": "https://epicproxy-pub.et0502.epichosted.com/EPPARRPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC",
      "name": "UC Health (San Diego / Irvine / Riverside) and Affiliates",
      "canonical_iss": "https://epicproxy.et0502.epichosted.com/EPPARRPRD/api/epic/2021/Security/Open/EcKeys/32001/SHC"
    }
```

?

**Comment by p2-apple** [comment]
I think I would expect your second post, with both `iss` still present. This prevents "old" clients from breaking but allows to do more once `canonical_iss` is supported.

**Comment by isaacvetter** [comment]
Thanks, @p2-apple ! I'd realized this myself while thinking about it over lunch. Updated the above.

**Comment by p9g** [comment]
Do we trust all issuers to issue both vaccinations and lab tests?  Do we need the metadata to indicate which VC types https://spec.smarthealth.cards/vocabulary/ the issuer is trusted to issue?

**Comment by p2-apple** [comment]
> Do we trust all issuers to issue both vaccinations and lab tests? Do we need the metadata to indicate which VC types https://spec.smarthealth.cards/vocabulary/ the issuer is trusted to issue?

That's still an open question, see [my comment above on `healthCardTypes`](https://github.com/the-commons-project/vci-directory/issues/52#issuecomment-911283109).

**Comment by isaacvetter** [comment]
Until, unless we have something like `healthCardTypes`, yes, issuers are trusted for any SHCs they issue. Any other interpretation forces verifiers/wallets to create their own allowlists (aka directories). Right?

**Comment by BenjaminatEpic** [comment]
@jdkizer9 Could we update https://github.com/the-commons-project/vci-directory/blob/main/example-issuer.json to reflect the new metadata and formatting?
