### ISSUE TITLE
Update Validation SDK name and URL

### ISSUE THREAD

**Issue by christianpaquin** [the-commons-project/vci-directory#58]
The Health Cards Validation SDK was renamed to Health Cards Dev Tools, so point 4 of the [VCI agreement](https://github.com/the-commons-project/vci-directory/blob/main/VCI%20Directory%20Agreement.pdf) should now read:

`SHCs issued by Issuer have gone through a quality assurance process to ensure correctness in addition to the validation using the developer tools, available at https://github.com/smart-on-fhir/health-cards-dev-tools and as a portal at https://demo-portals.smarthealth.cards/VerifierPortal.html.`

**Comment by jdkizer9** [comment]
Hi @christianpaquin, could you please take a look at #103 ? Thanks!

**Comment by christianpaquin** [comment]
Looks good.
