### ISSUE TITLE
Malformed vci-issuers-metadata.json files

### ISSUE THREAD

**Issue by bfree-github** [the-commons-project/vci-directory#787]
We have a SMART verifier app (https://vizcat.com) that we launched in July 2021 - and have been using your vci-directory as a way to verify SMART issuers.

In the past month we've been encountering issues with your vci-issuers-metadata.json file:

1. We had assumed that your vci-issuers-metadata.json and vci-issuers.json files were in sync, and was using an index to look up records in the other.  This appears to no longer be the case (vci-issuers.json is 2 records longer than vci-issuers-metadata.json), so now we're using the iss field.

2. More importantly, we're now seeing malformed vci-issuers-metadata.json files (in the latest case a trailing comma in an array), which breaks JSON parsers.  This makes it difficult to rely on your registry for validation.

Can you please add a test to check that your JSON is valid before checking this in?

Thanks!

**Comment by bfree-github** [comment]
We've encountered another malformed vci-issuers-metadata.json file with a missing comma (before locations) this time:

        {
            "canonical_iss":"https://epicproxy.et0927.epichosted.com/FHIRProxy/api/epic/2021/Security/Open/EcKeys/32001/SHC",
            "issuer_type":"organizational.health_system",
            "website":"https://myhss.hss.edu/MyHSS/"
            "locations":[
                {
                    "state":"NY",
                    "country":"US"
                }
            ]
        },

**Comment by bfree-github** [comment]
Also missing a comma here:

                }
                    {
                    "state":"KS",
                    "country":"US"
                }

**Comment by bfree-github** [comment]
Let us know if you need help managing your json files; they are currently unusable.

**Comment by edwardjcruz** [comment]
@bfree-github these errors have now been resolved. We'll be implementing a json validation check shortly on each PR moving forward. Thank you for pointing out these issues!
