### ISSUE TITLE
Add Government of BC, Canada Issuer 

### ISSUE THREAD

**Issue by ninosamson** [the-commons-project/vci-directory#888]
Hi there - we noticed that the Government of BC is no longer on the issuers.json. 

Can you please add the public URL? 

      "iss": "https://smarthealthcard.phsa.ca/v1/issuer/.well-known/jwks.json",
      "name": "Government of BC",
      "website": "https://www.healthgateway.gov.bc.ca/"

**Comment by laurencebgood** [comment]
Look at #30 and you will see that unfortunately BC wants to be excluded.

**Comment by ninosamson** [comment]
Hi - thanks for the quick reply. It's odd as the BC issuer seemed to be recognized until recently.

I'll get Brad to comment so we can get added back. We do want to be included as a recognized issuer.

@Bradhead

**Comment by ninosamson** [comment]
@laurencebgood will adding the issuer to the repo result in the app recognizing BC QRs, or do I need to reach out to someone else separately?

**Comment by laurencebgood** [comment]
> @laurencebgood will adding the issuer to the repo result in the app recognizing BC QRs, or do I need to reach out to someone else separately?

(I'm not a representative of the vci, I am just an interested independent, so take with a grain of salt)

Last I checked that process is still independent and not transparent the way this repo is, so I don't know the answer. That's probably better to raise on #30 where it was previously discussed that they would ultimately be in sync.

I certainly would like BC to be recognized and also for BC to recognize other issuers. When I was last there it was pretty annoying that the provincial verifier didn't accept anything from the US or even other provinces. Most businesses were understanding but a few it was almost a fight
