### ISSUE TITLE
404 when requesting vci-issuers.json

### ISSUE THREAD

**Issue by zach-betz-hln** [the-commons-project/vci-directory#946]
edit: see this [comment](https://github.com/the-commons-project/vci-directory/issues/946#issuecomment-2364549862) for more nuance. 

---

## Steps to reproduce

1. Go to https://vci.org/issuers/

## Screenshots

Console:

![Screenshot 2024-02-15 at 2 16 21 PM](https://github.com/the-commons-project/vci-directory/assets/119352232/8beb1641-6a63-4e81-9deb-e30f7bdbc86a)

Request URL:
https://vci.org/issuers/data/vci-issuers.json

![Screenshot 2024-02-15 at 2 16 31 PM](https://github.com/the-commons-project/vci-directory/assets/119352232/81cc8bb4-05e6-428a-9e88-be299f8bb5b3)

Request URL:
https://vci.org/issuers/data/vci-issuers-metadata.json

![Screenshot 2024-02-15 at 2 16 38 PM](https://github.com/the-commons-project/vci-directory/assets/119352232/afe312ae-e259-4828-bba6-de0c7acfb37b)

**Comment by zach-betz-hln** [comment]
This is working now 🥳

**Comment by zach-betz-hln** [comment]
Reopening. This seems to be happening again.

Screenshot: 
![Screenshot 2024-02-16 at 8 06 58 AM](https://github.com/the-commons-project/vci-directory/assets/119352232/2e675062-07bf-41b7-8269-0cb6d27d0a11)

**Comment by zach-betz-hln** [comment]
Checking in - this still seems to be broken. 

Looking at your `.github/workflows` folder, I'm guessing the website is deployed with a mix of aws s3 + github pages?

Let me know if you'd like a hand sifting through the build logs. Would be glad to help.

**Comment by zach-betz-hln** [comment]
Friendly bump.

**Comment by jpp9** [comment]
thanks! @masnick can you remove the code block that’s producing the error, since the page is no longer trying to _display_ the issuers?

**Comment by zach-betz-hln** [comment]
Going out on a limb here, cc'ing @surfdoc as you seem to be active lately 🙂 - if you have any thoughts on this issue?

**Comment by jpp9** [comment]
thanks for keeping at this... we can't help directly with that website, but trying @masnick and perhaps @radamson to help get us to someone who can!?

**Comment by zach-betz-hln** [comment]
Thanks @jpp9 

If it helps, I was poking around the site and noticed some interesting behavior. Where _sometimes_ the issuers list loads 🤷‍♂️: 

## Scenario 1

1. Go to `https://vci.org/issuers/` - note the trailing slash
2. This fetch request fails `https://vci.org/issuers/data/vci-issuers.json`
3. The issuers list is forever loading

<img width="1728" alt="Screenshot 2024-09-20 at 3 08 05 PM" src="https://github.com/user-attachments/assets/67916012-d3f1-4bb5-9456-9a4958390bb9">


## Scenario 2

1. Go to `https://vci.org/`
2. Click Issuers in the top nav, which redirects to `https://vci.org/issuers` - notice there is no trailing slash
3. This fetch request succeeds `https://vci.org/data/vci-issuers.json`
4. The issuers list loads okay

<img width="1728" alt="Screenshot 2024-09-20 at 3 09 12 PM" src="https://github.com/user-attachments/assets/3f0af89a-c4ad-4e1c-89b1-1bf2b9eb2133">

## Notes

The fetch request is different for each as well. 

This 404s:

```
https://vci.org/issuers/data/vci-issuers.json
```

vs this, which works:

```
https://vci.org/data/vci-issuers.json
```

**Comment by zach-betz-hln** [comment]
Closing this, since the same list that VCI would display is now covered by: 

> Want to find an Issuer based off your location? Check out SMART Health's ["Find My Issuer" page ](https://smarthealth.cards/en/find-my-issuer.html).

**Comment by radamson** [comment]
> thanks for keeping at this... we can't help directly with that website, but trying @masnick and perhaps @radamson to help get us to someone who can!?

I'm no longer at MITRE, so I'm not in control of the website. I can try to find out who is though!

**Comment by masnick** [comment]
Hi @radamson @jpp9 -- I can probably get this sorted.

Max
